mod_name = "Plushed"
mod_id = "plushed"
mod_group = "org.teamvoided"
mod_version = "1.0.0"
mod_description = "Im going to turn all of you in to marketable plushies"
github_repo = "Teamvoided/Plushed"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.11 <26.1"
